apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-chart.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "weather-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http

